using Godot;

namespace SharedUtils.Common
{
    public enum ErrorCode
    {
        Ok = Error.Ok,
        Failed = Error.Failed,
        Unavailable = Error.Unavailable,
        Unconfigured = Error.Unconfigured,
        Unauthorized = Error.Unauthorized,
        ParameterRangeError = Error.ParameterRangeError,
        OutOfMemory = Error.OutOfMemory,
        FileNotFound = Error.FileNotFound,
        FileBadDrive = Error.FileBadDrive,
        FileBadPath = Error.FileBadPath,
        FileNoPermission = Error.FileNoPermission,
        FileAlreadyInUse = Error.FileAlreadyInUse,
        FileCantOpen = Error.FileCantOpen,
        FileCantWrite = Error.FileCantWrite,
        FileCantRead = Error.FileCantRead,
        FileUnrecognized = Error.FileUnrecognized,
        FileCorrupt = Error.FileCorrupt,
        FileMissingDependencies = Error.FileMissingDependencies,
        FileEof = Error.FileEof,
        CantOpen = Error.CantOpen,
        CantCreate = Error.CantCreate,
        QueryFailed = Error.QueryFailed,
        AlreadyInUse = Error.AlreadyInUse,
        Locked = Error.Locked,
        Timeout = Error.Timeout,
        CantConnect = Error.CantConnect,
        CantResolve = Error.CantResolve,
        ConnectionError = Error.ConnectionError,
        CantAcquireResource = Error.CantAcquireResource,
        CantFork = Error.CantFork,
        InvalidData = Error.InvalidData,
        InvalidParameter = Error.InvalidParameter,
        AlreadyExists = Error.AlreadyExists,
        DoesNotExist = Error.DoesNotExist,
        DatabaseCantRead = Error.DatabaseCantRead,
        DatabaseCantWrite = Error.DatabaseCantWrite,
        CompilationFailed = Error.CompilationFailed,
        MethodNotFound = Error.MethodNotFound,
        LinkFailed = Error.LinkFailed,
        ScriptFailed = Error.ScriptFailed,
        CyclicLink = Error.CyclicLink,
        InvalidDeclaration = Error.InvalidDeclaration,
        DuplicateSymbol = Error.DuplicateSymbol,
        ParseError = Error.ParseError,
        Busy = Error.Busy,
        Skip = Error.Skip,
        Help = Error.Help,
        Bug = Error.Bug,
        PrinterOnFire = Error.PrinterOnFire,
        CantSave = 49,
        EnvironmentVariableNotSet = 50,
        DirBadPath = 51,
        DataTooLong = 52,
        MissingAttribute = 53,
        NotValid = 54,
    }
}
